#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require_relative '../lib/ssh_key_switcher'

# Prevent failures from being reported twice.
Thread.report_on_exception = false

begin
  SshKeySwitcher::CLI.start(ARGV)
rescue StandardError => e
  puts "  \e[31mERROR (#{e.class}): #{e.message}\e[0m"
  exit 1
end
